Hostel/Controllers/HostelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hostel.Controllers
{
    public class HostelController : Controller
    {
        // GET: Hostel
        public ActionResult Index()
        {
            if ((string)Session["type"]=="Admin") {
                HostelDBContext context = new HostelDBContext();
                Hostel hostel = context.Hostels.SingleOrDefault(h => h.HostelId == 1);
                return View(hostel);
            }
            else
            {
                return Redirect("/User/Error");
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if ((string)Session["type"] == "Admin")
            {
                HostelDBContext context = new HostelDBContext();
                Hostel hostel = context.Hostels.SingleOrDefault(h => h.HostelId == id);
                return View(hostel);
            }
            else
            {
                return Redirect("/User/Error");
            }
        }
        [HttpPost,ActionName("Edit")]
        public ActionResult Update(int id, HttpPostedFileBase file)
        {
            if ((string)Session["type"] == "Admin")
            {
                HostelDBContext context = new HostelDBContext();
                Hostel hostel= context.Hostels.SingleOrDefault(h => h.HostelId == id);

                try
                {

                    if (Request.Files.Count > 0)
                    {
                        var Inputfile = Request.Files[0];

                        if (Inputfile != null && Inputfile.ContentLength > 0)
                        {
                            if (System.IO.File.Exists("~/Uploads/Logos"+hostel.HostelLogo))
                            {
                                System.IO.File.Delete("~/Uploads/Logos" + hostel.HostelLogo);
                            }
                            var filename = Path.GetFileName(Inputfile.FileName);
                            var path = Path.Combine(Server.MapPath("~/Uploads/Logos"), "hostellogo" + Path.GetExtension(Inputfile.FileName));
                            Inputfile.SaveAs(path);
                            hostel.HostelLogo = "hostellogo" + Path.GetExtension(Inputfile.FileName);
                        }

                    }

                }
                catch (Exception)
                {

                    TempData["Failed"] = "Failed To Upload Logo";

                }

                TryUpdateModel(hostel);

                if (ModelState.IsValid)
                {
                    context.SaveChanges();
                    Session["HostelTitle"] = hostel.HostelTitle;
                    TempData["Success"] = "Hostel Info Successfully Updated!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(hostel);
                }
                
            }
            else
            {
                return Redirect("/User/Error");
            }
        }
        
    }
}

Hostel/Views/Hostel/Edit.cshtml
@model Hostel

@{
    ViewBag.Title = "Update Hostel Information";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Update Hostel Information</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    @using (Html.BeginForm("Edit", "Hostel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal col-sm-8">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.HostelId)

            <div class="form-group">
                @Html.LabelFor(model => model.HostelName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HostelName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HostelName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HostelTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HostelTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HostelTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Road, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Road, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Road, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.House, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.House, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.House, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HostelLogo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="~/Uploads/Logos/@Html.DisplayFor(model => model.HostelLogo)" class="img-thumbnail" alt="logo" width="250" height="200" />
                    @Html.TextBox("file", "", new { type = "file" }) <br />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info btn-large" })
                </div>
            </div>
        </div>
    }
</div>

Hostel/Views/Hostel/Index.cshtml
@model Hostel

@{
    ViewBag.Title = "Hostel Info";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Hostel Information</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<h4>
    <div class="row">
        <dl class="dl-horizontal bg-success" style="padding:20px">
            
            <dt>
                @Html.DisplayNameFor(model => model.HostelName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HostelName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HostelTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HostelTitle)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Area)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Area)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Road)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Road)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.House)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.House)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HostelLogo)
            </dt>
            <dd>
                <img src="~/Uploads/Logos/@Html.DisplayFor(model => model.HostelLogo)" class="img-thumbnail" alt="logo" width="250" height="200" />
            </dd>

        </dl>
    </div>
</h4>
<p>
    <h4>@Html.ActionLink("Edit Hostel Info", "Edit", new { id = Model.HostelId } , new { @class = "btn btn-info btn-large" })</h4>  

</p>